### ISSUE TITLE
Delete assets funtionality is not working

### ISSUE THREAD

**Issue by vkoukos** [alexandrosraikos/policycloud-marketplace#105]
The "delete assets" functionality is not working either from the form or from the modals (for images/videos). No delete request is made at all... we can sync if you want to.

**Comment by vkoukos** [comment]
it doesn't work for images + videos and sometimes it doesn't work for the files either...
when you delete the first file / when you delete all files the error of the second image occurs

![delete](https://user-images.githubusercontent.com/90182603/146371540-bfec5f92-9ef6-4397-b9a3-550d1a2f3217.JPG)
![invalid json](https://user-images.githubusercontent.com/90182603/146371544-a6c9ed9c-9a76-485f-a6c1-b330a36433d5.JPG)

**Comment by alexandrosraikos** [comment]
NOTE: Still hanging on completion.
