### ISSUE TITLE
Different background color (white) for statistics section in homepage

### ISSUE THREAD

**Issue by vkoukos** [alexandrosraikos/policycloud-marketplace#107]
![image](https://user-images.githubusercontent.com/90182603/146017663-ac19aa31-5eaa-4895-a893-9889f44900e6.png)

**Comment by alexandrosraikos** [comment]
This requires a breakdown of the featured descriptions shortcode, assigning to 1.3.0.

**Comment by alexandrosraikos** [comment]
☑️ Option 1 (easy): Add CSS background. 
Option 2 (hard): Break down the featured descriptions shortcode and persist statistics to avoid multiple API calls.

**Comment by alexandrosraikos** [comment]
Easy option selected, need to follow up in the testing env.
